version: "3.9"
services:
  mysql-db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      # HOST_PORT:CONTAINER_PORT
      - 3306:3306
  phpMyAdmin:
    container_name: myadmin2
    image: phpmyadmin
    restart: always
    ports:
      - 8010:80
    links:
      - mysql-db:db